name: Print IP

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: AWS CLI
      uses: chrislennon/action-aws-cli@v1.1
    - run: aws s3 ls
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
    - name: Print a greeting
      env:
        EC2_Instance_IP: $(aws ec2 describe-addresses --query "Addresses[*].PublicIp" --output text)
      run: |
        echo ${{ env.EC2_Instance_IP }} 
